# Site settings
title:       Alan Wright
email:       alanwright47@gmail.com
author:      Alan Wright
description: "A personal site and blog for Alan Wright."
baseurl:     ""
url:         "http://alan-wright.com"

# Google analytics
google_analytics: "UA-32735185-1"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: false
github_username: alanwright
twitter_username: iamalanwright
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true